### ISSUE TITLE
Max upper limit of dynamically allocate swap

### ISSUE THREAD

**Issue by hhoffstaette** [Tookmund/Swapspace#21] opened 2020-04-09 13:22 UTC
I couldn't find an appropriate option for this, so: is there a way to limit the maximum amount
of swap that is dynamically allocated in total? This would be good to prevent a runaway
task from allocating TBs of disk space.

**Comment by Tookmund** [comment] 2020-04-09 14:14
Duplicate of #17

**Closed by Tookmund** 2020-04-09 14:14 UTC
